apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-server.fullname" . }}
  labels:
    {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discovery-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "discovery-server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}