apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-server.fullname" . }}
  labels:
    app: {{ include "discovery-server.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "discovery-server.selectorLabels" . | nindent 4 }}