apiVersion: v2
name: bankapp-umbrella
description: An umbrella chart for bankapp
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "12.1.0"
    alias: "bankapp-db"
  - name: discovery-server
    version: "1.0.0"
    repository: "file://charts/discovery-server"
  - name: config-server
    version: "1.0.0"
    repository: "file://charts/config-server"
  - name: blocker-service
    version: "1.0.0"
    repository: "file://charts/blocker-service"
  - name: notification-service
    version: "1.0.0"
    repository: "file://charts/notification-service"
  - name: account-service
    version: "1.0.0"
    repository: "file://charts/account-service"