spring:
  application:
    name: exchange-generator-service

server:
  port: 8083

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info
#  endpoint:
#    health:
#      show-details: always

exchange:
  main-currency: RUB
  rates:
    USD:
      min: 80
      max: 100
    CNY:
      min: 10
      max: 15