server:
#  port: 0
  port: 8080

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always