spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: transfer
    sql:
      init:
        mode: always

server:
  port: 8086

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info
#  endpoint:
#    health:
#      show-details: always