#spring:
#  application:
#    name: blocker-service

server:
  port: 8085

spring:
  application:
    name: blocker-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

blocker:
  min-threshold: 10
  max-threshold: 10000