apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}-config
data:
  application.yml: |
    server:
      port: 8080

    spring:
      application:
        name: blocker-service

    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          show-details: always

    blocker:
      min-threshold: 10
      max-threshold: 10000