apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blocker-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "blocker-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /config/application.yml
              subPath: application.yml
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config
          configMap:
            name: {{ include "blocker-service.fullname" . }}-config