services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true #-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "C:/Users/Dmitry/dev/YP Java Middle/bankapp:/repo:rw"
      - "C:/Users/Dmitry/dev/YP Java Middle/bankapp/jenkins/kubeconfig.yaml:/root/.kube/config"

volumes:
  jenkins_home: