-- DROP
-- DROP TABLE IF EXISTS accounts.users;
-- DROP SCHEMA IF EXISTS accounts;

-- CREATE
CREATE SCHEMA IF NOT EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts.users
(
    id UUID PRIMARY KEY,
    login VARCHAR(16) NOT NULL UNIQUE,
    password_hash VARCHAR(16) NOT NULL,
    name VARCHAR(32) NOT NULL,
    birthdate DATE NOT NULL,
    CONSTRAINT LOGIN_UNIQUE UNIQUE (LOGIN)
);