spring:
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: notification-server
      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"